#!/usr/bin/sh

# Automatically create /package/release with proper
# PKGBUILD and assets

pkgver=$(jq --raw-output ".info.productVersion" wails.json)
projname=$(jq --raw-output ".outputfilename" wails.json)

copy_files() {
	echo "Copying build and assets..."

	mkdir package/release/dist

	cp -r build/bin/* package/release/dist
	cp -r package/assets/* package/release/dist
	
	cp LICENSE package/release/dist
	cp README.md package/release/dist
	cp package/scripts/pacman/PKGBUILD-bin package/release/PKGBUILD

	echo "Done"
}

create_tar() {
	echo "Creating tar..."

	# Ensure file will always be named "quatracker"
	mv package/release/dist/"$projname" package/release/dist/quatracker

	cd package/release/dist || exit 1
	tar -czvf ../quatracker-"$pkgver"-amd64.tar.gz .
	cd - || exit 1

	echo "Done"
}

update_data() {
	echo "Writing PKGBUILD..."

	shaa=$(sha256sum package/release/quatracker-"$pkgver"-amd64.tar.gz | awk '{print $1}')

	sed -i "s/pkgver=/pkgver=$pkgver/" package/release/PKGBUILD
	sed -i "s/sha256sums=/sha256sums=(\"$shaa\")/" package/release/PKGBUILD

	echo "Done \`pkgver=$pkgver | sha256sum=$shaa\`"
}

copy_files
create_tar
update_data
