// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {config} from '../models';
import {images} from '../models';

export function GetBestScores(arg1:number,arg2:number,arg3:number,arg4:string,arg5:string,arg6:number):Promise<Array<database.ScoreBoard>>;

export function GetConfig():Promise<config.Config>;

export function GetGradeCount(arg1:number,arg2:number,arg3:boolean):Promise<database.GradesCountStat>;

export function GetJudgesCountStats(arg1:number,arg2:number):Promise<database.JudgeCountStat>;

export function GetLongestStats(arg1:number,arg2:number):Promise<database.LongestStat>;

export function GetMostPlayed(arg1:number,arg2:number,arg3:number):Promise<Array<database.MostPlayed>>;

export function GetOverallStats(arg1:number,arg2:number):Promise<database.OverallStats>;

export function GetPlayStats(arg1:number,arg2:number):Promise<database.PlayStats>;

export function GetRecentScores(arg1:number,arg2:number,arg3:number,arg4:boolean):Promise<database.CountedScoreBoard>;

export function GetScoreDetails(arg1:number):Promise<database.ScoreDetails>;

export function GetTotalStats(arg1:number,arg2:number):Promise<database.TotalStats>;

export function GetUserJudgements():Promise<Array<string>>;

export function GetUserPlayGraph(arg1:number,arg2:number):Promise<Record<string, number>>;

export function GetUsers():Promise<database.Users>;

export function LoadDB():Promise<void>;

export function NewImages():Promise<images.FileLoader>;

export function SetGamePath(arg1:string):Promise<void>;

export function SetMainMode(arg1:boolean):Promise<void>;
