// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBestScores(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['GetBestScores'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetGradeCount(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetGradeCount'](arg1, arg2, arg3);
}

export function GetJudgesCountStats(arg1, arg2) {
  return window['go']['app']['App']['GetJudgesCountStats'](arg1, arg2);
}

export function GetLongestStats(arg1, arg2) {
  return window['go']['app']['App']['GetLongestStats'](arg1, arg2);
}

export function GetMostPlayed(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetMostPlayed'](arg1, arg2, arg3);
}

export function GetOverallStats(arg1, arg2) {
  return window['go']['app']['App']['GetOverallStats'](arg1, arg2);
}

export function GetPlayStats(arg1, arg2) {
  return window['go']['app']['App']['GetPlayStats'](arg1, arg2);
}

export function GetRecentScores(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetRecentScores'](arg1, arg2, arg3, arg4);
}

export function GetScoreDetails(arg1) {
  return window['go']['app']['App']['GetScoreDetails'](arg1);
}

export function GetTotalStats(arg1, arg2) {
  return window['go']['app']['App']['GetTotalStats'](arg1, arg2);
}

export function GetUserJudgements() {
  return window['go']['app']['App']['GetUserJudgements']();
}

export function GetUserPlayGraph(arg1, arg2) {
  return window['go']['app']['App']['GetUserPlayGraph'](arg1, arg2);
}

export function GetUsers() {
  return window['go']['app']['App']['GetUsers']();
}

export function LoadDB() {
  return window['go']['app']['App']['LoadDB']();
}

export function NewImages() {
  return window['go']['app']['App']['NewImages']();
}

export function SetGamePath(arg1) {
  return window['go']['app']['App']['SetGamePath'](arg1);
}

export function SetMainMode(arg1) {
  return window['go']['app']['App']['SetMainMode'](arg1);
}
