#!/usr/bin/env node

// Very simple wails.json parser, no need for jq.
//  parse "frontend:dev:watcher" # -> pnpm run dev
process.stdout.write(
    require("../wails.json")[process.argv.slice(2)[0] || "name"]
);
